"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script – loads each model under its own params namespace,
// normalises it to the grid cell size, and positions it in a grid.
const { gridPosition, normalizeAndPlace, urlToPartName } = require('../../../lib/grid-utils.js')

const items = [
  "./tripod_mounts-ex.scad",
  "./tube.scad",
  "./up-down.scad",
  "./vnf-polyhedron.scad",
  "./vnf-vertex-array.scad",
  "./walls-ex.scad",
  "./wedge.scad",
  "./wiring-ex.scad",
  "./xcopies.scad",
  "./xcyl.scad",
  "./xrot-yrot-zrot.scad",
  "./ycopies.scad",
  "./ycyl.scad",
  "./zcopies.scad",
  "./zcyl.scad",
  "./cuboid.scad",
  "./cyl.scad",
  "./fillet.scad",
  "./octahedron.scad",
  "./onion.scad",
  "./pie-slice.scad",
  "./prismoid.scad",
  "./rect-tube.scad",
  "./regular-prism.scad",
  "./sphere.scad",
  "./spheroid.scad",
  "./teardrop.scad",
  "./tripod_mounts-ex.scad",
  "./tube.scad",
  "./up-down.scad",
  "./vnf-polyhedron.scad",
  "./vnf-vertex-array.scad",
  "./walls-ex.scad",
  "./wedge.scad",
  "./wiring-ex.scad",
  "./xcopies.scad",
  "./xcyl.scad",
  "./xrot-yrot-zrot.scad",
  "./ycopies.scad",
  "./ycyl.scad",
  "./zcopies.scad",
  "./zcyl.scad"
]
const spacing = 60
const cellSize = 51

const main = (params) => {
  const all = []
  const nameSeen = {}

  items.forEach((url, i) => {
    try {
      // Calculate grid position dynamically
      const [x, y] = gridPosition(i, items.length, spacing)

      // Derive unique part name from URL
      let name = urlToPartName(url)
      // Deduplicate: if the same name appears twice, append _2, _3, …
      if (nameSeen[name]) {
        nameSeen[name]++
        name = `${name}_${nameSeen[name]}`
      } else {
        nameSeen[name] = 1
      }

      const mod = require(url)
      const fn = (mod && mod.main) || (typeof mod === 'function' ? mod : null)
      if (typeof fn === 'function') {
        // For hierarchical models: pass child proxy
        // For legacy models: wrapLegacyModule detects child proxy and creates isolated state
        const geoms = [].concat(fn(params[name]))
        all.push(...normalizeAndPlace(geoms, x, y, cellSize))
      }
    } catch (err) {
      console.error('ALL: failed to load', url, err.message)
      throw new Error(`Failed to load ${url}: ${err.message}`)
    }
  })
  return all
}

module.exports = { main }
