"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script – loads each model under its own params namespace,
// normalises it to the grid cell size, and positions it in a grid.
const { gridPosition, normalizeAndPlace, urlToPartName, failureMarker, prebuiltSkull } = require('../../../../lib/grid-utils.js')

const items = [
  "./7_segments.scad",
  "./BLDC_motors.scad",
  "./BOM.scad",
  "./DIP.scad",
  "./HT_pipes.scad",
  "./IECs.scad",
  "./LDRs.scad",
  "./LED_bezel.scad",
  "./LED_meters.scad",
  "./LEDs.scad",
  "./PCB.scad",
  "./PCB_mount.scad",
  "./PCB_utils.scad",
  "./PSU_shroud.scad",
  "./PSUs.scad",
  "./SBR_rails.scad",
  "./SK_brackets.scad",
  "./SMDs.scad",
  "./SSR_shroud.scad",
  "./SSRs.scad",
  "./Swiss_clips.scad",
  "./annotation.scad",
  "./antennas.scad",
  "./axials.scad",
  "./ball_bearings.scad",
  "./batteries.scad",
  "./bearing_blocks.scad",
  "./belts.scad",
  "./bezier.scad",
  "./blowers.scad",
  "./box.scad",
  "./box_sections.scad",
  "./bulldogs.scad",
  "./butt_box.scad",
  "./buttons.scad",
  "./cable_clip.scad",
  "./cable_grommets.scad",
  "./cable_strips.scad",
  "./camera_housing.scad",
  "./cameras.scad",
  "./carriers.scad",
  "./catenary.scad",
  "./chamfer.scad",
  "./circlips.scad",
  "./clip.scad",
  "./components.scad",
  "./core_xy.scad",
  "./corner_block.scad",
  "./d_connectors.scad",
  "./dimension.scad",
  "./displays.scad",
  "./dogbones.scad",
  "./door_hinge.scad",
  "./door_latch.scad",
  "./drag_chain.scad",
  "./extrusion_brackets.scad",
  "./extrusions.scad",
  "./fan_guard.scad",
  "./fans.scad",
  "./fastons.scad",
  "./fillet.scad",
  "./fixing_block.scad",
  "./flat_hinge.scad",
  "./foot.scad",
  "./fuseholder.scad",
  "./gear_motors.scad",
  "./geared_steppers.scad",
  "./gears.scad",
  "./global.scad",
  "./green_terminals.scad",
  "./gridfinity.scad",
  "./handle.scad",
  "./hanging_hole.scad",
  "./horiholes.scad",
  "./hot_ends.scad",
  "./hygrometer.scad",
  "./inserts.scad",
  "./jack.scad",
  "./knob.scad",
  "./layout.scad",
  "./leadnuts.scad",
  "./light_strips.scad",
  "./linear_bearings.scad",
  "./magnets.scad",
  "./mains_sockets.scad",
  "./maths.scad",
  "./microswitches.scad",
  "./microview.scad",
  "./modules.scad",
  "./nuts.scad",
  "./o_ring.scad",
  "./offset.scad",
  "./opengrab.scad",
  "./panel_meters.scad",
  "./photo_interrupters.scad",
  "./pillars.scad",
  "./pillow_blocks.scad",
  "./pin_headers.scad",
  "./pocket_handle.scad",
  "./polyholes.scad",
  "./potentiometers.scad",
  "./press_fit.scad",
  "./printed_box.scad",
  "./printed_pulleys.scad",
  "./pulleys.scad",
  "./quadrant.scad",
  "./radials.scad",
  "./rails.scad",
  "./ribbon_clamp.scad",
  "./ring_terminals.scad",
  "./rockers.scad",
  "./rod.scad",
  "./rod_ends.scad",
  "./round.scad",
  "./rounded_cylinder.scad",
  "./rounded_polygon.scad",
  "./rounded_rectangle.scad",
  "./rounded_triangle.scad",
  "./screw_knob.scad",
  "./screws.scad",
  "./sealing_strip.scad",
  "./sector.scad",
  "./servo_motors.scad",
  "./shaft_couplings.scad",
  "./sheets.scad",
  "./socket_box.scad",
  "./spades.scad",
  "./sphere.scad",
  "./splines.scad",
  "./spools.scad",
  "./springs.scad",
  "./stepper_motors.scad",
  "./strap_handle.scad",
  "./sweep.scad",
  "./teardrops.scad",
  "./terminals.scad",
  "./thread.scad",
  "./toggles.scad",
  "./transformers.scad",
  "./ttracks.scad",
  "./tube.scad",
  "./tubings.scad",
  "./variacs.scad",
  "./veroboard.scad",
  "./washers.scad",
  "./wire.scad",
  "./zipties.scad"
]
const spacing = 60
const cellSize = 51

const isWasmTrap = (err) =>
  (typeof WebAssembly !== 'undefined' && err instanceof WebAssembly.RuntimeError) || err?.name === 'RuntimeError'

// Once the wasm has trapped, a built marker would need it too
const markerFor = (x, y) => {
  if (!globalThis.__allWasmTrap) {
    try {
      return normalizeAndPlace(failureMarker(), x, y, cellSize)
    } catch { /* fall back to the stored skull */ }
  }
  return [prebuiltSkull(x, y, cellSize)]
}

const main = async (params) => {
  // Only the outermost grid streams; a nested grid arrives in it as one cell
  const stream = globalThis.__jscadStream
  globalThis.__jscadStream = null
  try {
    return await runCells(params, stream)
  } finally {
    globalThis.__jscadStream = stream
  }
}

const runCells = async (params, stream) => {
  const all = []
  const nameSeen = {}
  const failed = []
  const generation = globalThis.__jscadScriptGeneration

  const send = (geoms) => {
    if (!stream) {
      all.push(...geoms)
      return
    }
    try {
      stream.emit(geoms)
    } finally {
      for (const g of geoms) if (typeof g?.dispose === 'function') g.dispose()
    }
  }

  for (const [i, url] of items.entries()) {
    const [x, y] = gridPosition(i, items.length, spacing)

    try {
      let name = urlToPartName(url)
      if (nameSeen[name]) {
        nameSeen[name]++
        name = `${name}_${nameSeen[name]}`
      } else {
        nameSeen[name] = 1
      }

      // A trapped wasm instance stays broken, so no later cell's result can be trusted
      if (globalThis.__allWasmTrap) throw new Error(`not run: wasm trapped in ${globalThis.__allWasmTrap}`)

      const mod = require(url)
      const fn = (mod && mod.main) || (typeof mod === 'function' ? mod : null)
      if (typeof fn === 'function') {
        const geoms = [].concat(await fn(params[name])).flat()
        // emit evaluates the cell's CSG, so its failures belong to this cell too
        send(normalizeAndPlace(geoms, x, y, cellSize))
      }
    } catch (err) {
      // One bad model marks its own cell; the rest of the grid still renders
      if (isWasmTrap(err)) globalThis.__allWasmTrap ??= url
      console.error(`ALL: FAILED ${url}: ${err.message}`)
      failed.push(url)
      try {
        send(markerFor(x, y))
      } catch (markerErr) {
        if (isWasmTrap(markerErr)) globalThis.__allWasmTrap ??= url
        send([prebuiltSkull(x, y, cellSize)])
      }
    }

    if (!stream) globalThis.__jscadProgress?.()
    // Manifold handles are freed by a FinalizationRegistry, which only runs once main yields
    await new Promise(r => setTimeout(r, 0))
    // Yielding lets a newer script start in this worker; stop rather than run beside it
    if (globalThis.__jscadScriptGeneration !== generation) throw new Error(`grid superseded by a newer script after ${url}`)
  }

  if (failed.length) {
    console.error(`ALL: ${failed.length}/${items.length} models failed: ${failed.join(' ')}`)
  }
  return stream ? [] : all
}

module.exports = { main }
