"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../../lib/grid-utils.js')

const items = [
  "./annotation.scad",
  "./bezier.scad",
  "./catenary.scad",
  "./chamfer.scad",
  "./clip.scad",
  "./core_xy.scad",
  "./dimension.scad",
  "./dogbones.scad",
  "./fillet.scad",
  "./gears.scad",
  "./global.scad",
  "./hanging_hole.scad",
  "./horiholes.scad",
  "./layout.scad",
  "./maths.scad",
  "./offset.scad",
  "./polyholes.scad",
  "./quadrant.scad",
  "./round.scad",
  "./rounded_cylinder.scad",
  "./rounded_polygon.scad",
  "./rounded_rectangle.scad",
  "./rounded_triangle.scad",
  "./sector.scad",
  "./sphere.scad",
  "./splines.scad",
  "./sweep.scad",
  "./teardrops.scad",
  "./thread.scad",
  "./tube.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
