"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script – loads each model under its own params namespace,
// normalises it to the grid cell size, and positions it in a grid.
const { gridPosition, normalizeAndPlace, urlToPartName } = require('../../../../lib/grid-utils.js')

const items = [
  "./7_segments.scad",
  "./BLDC_motors.scad",
  "./BOM.scad",
  "./DIP.scad",
  "./HT_pipes.scad",
  "./IECs.scad",
  "./LDRs.scad",
  "./LED_bezel.scad",
  "./LED_meters.scad",
  "./LEDs.scad",
  "./PCB.scad",
  "./PCB_mount.scad",
  "./PCB_utils.scad",
  "./PSU_shroud.scad",
  "./PSUs.scad",
  "./SBR_rails.scad",
  "./SK_brackets.scad",
  "./SMDs.scad",
  "./SSR_shroud.scad",
  "./SSRs.scad",
  "./Swiss_clips.scad",
  "./annotation.scad",
  "./antennas.scad",
  "./axials.scad",
  "./ball_bearings.scad",
  "./batteries.scad",
  "./bearing_blocks.scad",
  "./bezier.scad",
  "./blowers.scad",
  "./box.scad",
  "./box_sections.scad",
  "./bulldogs.scad",
  "./butt_box.scad",
  "./buttons.scad",
  "./cable_clip.scad",
  "./cable_grommets.scad",
  "./cable_strips.scad",
  "./camera_housing.scad",
  "./cameras.scad",
  "./carriers.scad",
  "./catenary.scad",
  "./chamfer.scad",
  "./circlips.scad",
  "./clip.scad",
  "./components.scad",
  "./core_xy.scad",
  "./corner_block.scad",
  "./d_connectors.scad",
  "./dimension.scad",
  "./displays.scad",
  "./dogbones.scad",
  "./door_hinge.scad",
  "./door_latch.scad",
  "./drag_chain.scad",
  "./extrusion_brackets.scad",
  "./extrusions.scad",
  "./fan_guard.scad",
  "./fans.scad",
  "./fastons.scad",
  "./fillet.scad",
  "./fixing_block.scad",
  "./flat_hinge.scad",
  "./foot.scad",
  "./fuseholder.scad",
  "./gear_motors.scad",
  "./geared_steppers.scad",
  "./gears.scad",
  "./global.scad",
  "./green_terminals.scad",
  "./gridfinity.scad",
  "./handle.scad",
  "./hanging_hole.scad",
  "./horiholes.scad",
  "./hot_ends.scad",
  "./hygrometer.scad",
  "./inserts.scad",
  "./jack.scad",
  "./knob.scad",
  "./layout.scad",
  "./leadnuts.scad",
  "./light_strips.scad",
  "./linear_bearings.scad",
  "./magnets.scad",
  "./mains_sockets.scad",
  "./maths.scad",
  "./microswitches.scad",
  "./microview.scad",
  "./modules.scad",
  "./nuts.scad",
  "./o_ring.scad",
  "./offset.scad",
  "./opengrab.scad",
  "./panel_meters.scad",
  "./photo_interrupters.scad",
  "./pillars.scad",
  "./pillow_blocks.scad",
  "./pin_headers.scad",
  "./pocket_handle.scad",
  "./polyholes.scad",
  "./potentiometers.scad",
  "./press_fit.scad",
  "./printed_box.scad",
  "./printed_pulleys.scad",
  "./pulleys.scad",
  "./quadrant.scad",
  "./radials.scad",
  "./rails.scad",
  "./ribbon_clamp.scad",
  "./ring_terminals.scad",
  "./rockers.scad",
  "./rod.scad",
  "./rod_ends.scad",
  "./round.scad",
  "./rounded_cylinder.scad",
  "./rounded_polygon.scad",
  "./rounded_rectangle.scad",
  "./rounded_triangle.scad",
  "./screw_knob.scad",
  "./screws.scad",
  "./sealing_strip.scad",
  "./sector.scad",
  "./servo_motors.scad",
  "./sheets.scad",
  "./socket_box.scad",
  "./spades.scad",
  "./sphere.scad",
  "./splines.scad",
  "./spools.scad",
  "./springs.scad",
  "./stepper_motors.scad",
  "./strap_handle.scad",
  "./sweep.scad",
  "./teardrops.scad",
  "./terminals.scad",
  "./thread.scad",
  "./toggles.scad",
  "./transformers.scad",
  "./ttracks.scad",
  "./tube.scad",
  "./tubings.scad",
  "./variacs.scad",
  "./veroboard.scad",
  "./washers.scad",
  "./wire.scad",
  "./zipties.scad"
]
const spacing = 60
const cellSize = 51

const main = (params) => {
  const all = []
  const nameSeen = {}

  items.forEach((url, i) => {
    try {
      // Calculate grid position dynamically
      const [x, y] = gridPosition(i, items.length, spacing)

      // Derive unique part name from URL
      let name = urlToPartName(url)
      // Deduplicate: if the same name appears twice, append _2, _3, …
      if (nameSeen[name]) {
        nameSeen[name]++
        name = `${name}_${nameSeen[name]}`
      } else {
        nameSeen[name] = 1
      }

      const mod = require(url)
      const fn = (mod && mod.main) || (typeof mod === 'function' ? mod : null)
      if (typeof fn === 'function') {
        // For hierarchical models: pass child proxy
        // For legacy models: wrapLegacyModule detects child proxy and creates isolated state
        const geoms = [].concat(fn(params[name])).flat()
        all.push(...normalizeAndPlace(geoms, x, y, cellSize))
      }
    } catch (err) {
      console.error('ALL: failed to load', url, err.message)
      throw new Error(`Failed to load ${url}: ${err.message}`)
    }
  })
  return all
}

module.exports = { main }
