"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../../lib/grid-utils.js')

const items = [
  "./box.scad",
  "./butt_box.scad",
  "./cable_clip.scad",
  "./cable_grommets.scad",
  "./camera_housing.scad",
  "./carriers.scad",
  "./corner_block.scad",
  "./door_hinge.scad",
  "./door_latch.scad",
  "./drag_chain.scad",
  "./fan_guard.scad",
  "./fixing_block.scad",
  "./flat_hinge.scad",
  "./foot.scad",
  "./gridfinity.scad",
  "./handle.scad",
  "./knob.scad",
  "./pocket_handle.scad",
  "./press_fit.scad",
  "./printed_box.scad",
  "./printed_pulleys.scad",
  "./ribbon_clamp.scad",
  "./screw_knob.scad",
  "./socket_box.scad",
  "./strap_handle.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
