"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../../lib/grid-utils.js')

const items = [
  "./BLDC_motors.scad",
  "./BOM.scad",
  "./DIP.scad",
  "./HT_pipes.scad",
  "./IECs.scad",
  "./LDRs.scad",
  "./LED_bezel.scad",
  "./LED_meters.scad",
  "./LEDs.scad",
  "./PCB.scad",
  "./PCB_mount.scad",
  "./PCB_utils.scad",
  "./PSU_shroud.scad",
  "./PSUs.scad",
  "./SBR_rails.scad",
  "./SK_brackets.scad",
  "./SMDs.scad",
  "./SSR_shroud.scad",
  "./SSRs.scad",
  "./Swiss_clips.scad",
  "./cable_strips.scad",
  "./terminals.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
