"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../lib/grid-utils.js')

const items = [
  "./024-math-in_list.scad",
  "./025-math-reverse.scad",
  "./026-math-enumerate.scad",
  "./027-math-flatten.scad",
  "./028-math-vmul.scad",
  "./029-math-vdiv.scad",
  "./030-math-triangle_area2d.scad",
  "./031-metric_screws-screw.scad",
  "./032-metric_screws-metric_bolt.scad",
  "./033-metric_screws-metric_nut.scad",
  "./034-nema_steppers-nema11_stepper.scad",
  "./035-nema_steppers-nema14_stepper.scad",
  "./036-nema_steppers-nema17_stepper.scad",
  "./037-nema_steppers-nema23_stepper.scad",
  "./038-nema_steppers-nema34_stepper.scad",
  "./039-nema_steppers-nema_mount_holes.scad",
  "./040-nema_steppers-nema11_mount_holes.scad",
  "./041-nema_steppers-nema14_mount_holes.scad",
  "./042-nema_steppers-nema17_mount_holes.scad",
  "./043-nema_steppers-nema23_mount_holes.scad",
  "./044-nema_steppers-nema34_mount_holes.scad",
  "./045-paths-trace_polyline.scad",
  "./046-paths-extrude_2d_hollow.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
