"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script – loads each model under its own params namespace,
// normalises it to the grid cell size, and positions it in a grid.
const { gridPosition, normalizeAndPlace, urlToPartName } = require('../../../lib/grid-utils.js')

const items = [
  "./Abacus.scad",
  "./Angle Shelf.scad",
  "./Arc_01.scad",
  "./Arc_02.scad",
  "./Arrow_01.scad",
  "./Banner_01.scad",
  "./Base_cabinet_01.scad",
  "./Base_cabinet_02.scad",
  "./Beam_Angular.scad",
  "./Beam_C.scad",
  "./Beam_H.scad",
  "./Beam_T.scad",
  "./Bed_01.scad",
  "./Bed_02.scad",
  "./Bench_01.scad",
  "./Bench_02.scad",
  "./Bookshelf_01.scad",
  "./Bookshelf_02.scad",
  "./Box_Wood_01.scad",
  "./Building_01.scad",
  "./Building_02.scad",
  "./Chair_01.scad",
  "./Chair_02.scad",
  "./Chair_03.scad",
  "./Chalkboard_01.scad",
  "./Chalkboard_02.scad",
  "./Circular_Blade.scad",
  "./Coin_01.scad",
  "./Coin_02.scad",
  "./Cone_01.scad",
  "./Crystal.scad",
  "./Cup_01.scad",
  "./Display_Seven_Segments.scad",
  "./Door_01.scad",
  "./Electric_Wire_Plug.scad",
  "./Eyebolt.scad",
  "./Fence_01.scad",
  "./Fence_02.scad",
  "./Fireplace_01.scad",
  "./Flag_France.scad",
  "./Flag_Italy.scad",
  "./Flange_01.scad",
  "./Flange_02.scad",
  "./Flange_03.scad",
  "./Floor_01.scad",
  "./Gear_01.scad",
  "./Gear_02.scad",
  "./Grid_01.scad",
  "./Hexagon_socket_screw_keys.scad",
  "./Hole_Plate.scad",
  "./Ingot_01.scad",
  "./Key.scad",
  "./Key_Old_01.scad",
  "./Key_Simple.scad",
  "./Ladder_01.scad",
  "./Ladder_02.scad",
  "./Lamp_01.scad",
  "./Led_01.scad",
  "./Letter_A.scad",
  "./Lever_Handle.scad",
  "./Mallet.scad",
  "./Mech_Piece_01.scad",
  "./Mech_Piece_02.scad",
  "./Mech_Piece_03.scad",
  "./Mech_Piece_04.scad",
  "./Mechanism_01.scad",
  "./Notebook.scad",
  "./Nut_LQ.scad",
  "./Pendulum.scad",
  "./Pipe_00.scad",
  "./Pipe_45.scad",
  "./Pipe_90.scad",
  "./Resistor.scad",
  "./Ring.scad",
  "./Rod_01.scad",
  "./Roll_Holder.scad",
  "./Sauce_Bottle.scad",
  "./Screw.scad",
  "./Sign_01.scad",
  "./Sign_02.scad",
  "./Sign_03.scad",
  "./Soda_Cup_01.scad",
  "./Sofa.scad",
  "./Stairs_01.scad",
  "./Stairs_02.scad",
  "./Stairs_03.scad",
  "./Street_01.scad",
  "./Street_02.scad",
  "./Street_03.scad",
  "./Street_04.scad",
  "./Street_05.scad",
  "./Street_06.scad",
  "./Sword_01.scad",
  "./Table_01.scad",
  "./Table_02.scad",
  "./Table_03.scad",
  "./Table_Small_01.scad",
  "./Tootbrush.scad",
  "./Tower.scad",
  "./Traffic_Light.scad",
  "./Transistor.scad",
  "./Tree_01.scad",
  "./Vent_Grid.scad",
  "./Walking_Stick.scad",
  "./Wall_01.scad",
  "./Wall_02.scad",
  "./Wall_03.scad",
  "./Wall_04.scad",
  "./Washer.scad",
  "./Weights_01.scad",
  "./Window_01.scad",
  "./x.scad"
]
const spacing = 60
const cellSize = 51

const main = (params) => {
  const all = []
  const nameSeen = {}

  items.forEach((url, i) => {
    try {
      // Calculate grid position dynamically
      const [x, y] = gridPosition(i, items.length, spacing)

      // Derive unique part name from URL
      let name = urlToPartName(url)
      // Deduplicate: if the same name appears twice, append _2, _3, …
      if (nameSeen[name]) {
        nameSeen[name]++
        name = `${name}_${nameSeen[name]}`
      } else {
        nameSeen[name] = 1
      }

      const mod = require(url)
      const fn = (mod && mod.main) || (typeof mod === 'function' ? mod : null)
      if (typeof fn === 'function') {
        // For hierarchical models: pass child proxy
        // For legacy models: wrapLegacyModule detects child proxy and creates isolated state
        const geoms = [].concat(fn(params[name])).flat()
        all.push(...normalizeAndPlace(geoms, x, y, cellSize))
      }
    } catch (err) {
      console.error('ALL: failed to load', url, err.message)
      throw new Error(`Failed to load ${url}: ${err.message}`)
    }
  })
  return all
}

module.exports = { main }
