"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../lib/grid-utils.js')

const items = [
  "./Scene_City_Street.scad",
  "./Scene_House.scad",
  "./Street_03.scad",
  "./Street_04.scad",
  "./Street_05.scad",
  "./Street_06.scad",
  "./Sword_01.scad",
  "./Table_01.scad",
  "./Table_02.scad",
  "./Table_03.scad",
  "./Table_Small_01.scad",
  "./Tootbrush.scad",
  "./Tower.scad",
  "./Traffic_Light.scad",
  "./Transistor.scad",
  "./Tree_01.scad",
  "./Vent_Grid.scad",
  "./Walking_Stick.scad",
  "./Wall_01.scad",
  "./Wall_02.scad",
  "./Wall_03.scad",
  "./Wall_04.scad",
  "./Washer.scad",
  "./Weights_01.scad",
  "./Window_01.scad",
  "./Wood_Crate.scad",
  "./x.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
