"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../../lib/grid-utils.js')

const items = [
  "./2_corner_wang_tiles_basic.scad",
  "./2_edge_wang_tiles_basic.scad",
  "./city_tile.scad",
  "./hitomezashi_stitching.scad",
  "./knot_tiles.scad",
  "./lavender.scad",
  "./magic_apartment.scad",
  "./penrose_basket.scad",
  "./penrose_crystallization.scad",
  "./random_city.scad",
  "./random_town_square.scad",
  "./tiled_line_mobius.scad",
  "./tiled_line_ring.scad",
  "./tiled_line_torus.scad",
  "./tiled_lines.scad",
  "./tiled_quarter_circles.scad",
  "./tiles_wfc_tube.scad",
  "./tube_box.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
