"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script – loads each model under its own params namespace,
// normalises it to the grid cell size, and positions it in a grid.
const { gridPosition, normalizeAndPlace, urlToPartName, failureMarker } = require('../../../../lib/grid-utils.js')

const items = [
  "./2_corner_wang_tiles_basic.scad",
  "./2_edge_wang_tiles_basic.scad",
  "./city_tile.scad",
  "./hitomezashi_stitching.scad",
  "./knot_tiles.scad",
  "./lavender.scad",
  "./magic_apartment.scad",
  "./penrose_basket.scad",
  "./penrose_crystallization.scad",
  "./random_city.scad",
  "./random_town_square.scad",
  "./tiled_line_mobius.scad",
  "./tiled_line_ring.scad",
  "./tiled_line_torus.scad",
  "./tiled_lines.scad",
  "./tiled_quarter_circles.scad",
  "./tiles_wfc_tube.scad",
  "./tube_box.scad"
]
const spacing = 60
const cellSize = 51

const isWasmTrap = (err) =>
  (typeof WebAssembly !== 'undefined' && err instanceof WebAssembly.RuntimeError) || err?.name === 'RuntimeError'

const main = (params) => {
  const all = []
  const nameSeen = {}
  const failed = []

  items.forEach((url, i) => {
    // Calculate grid position dynamically
    const [x, y] = gridPosition(i, items.length, spacing)

    try {
      // Derive unique part name from URL
      let name = urlToPartName(url)
      // Deduplicate: if the same name appears twice, append _2, _3, …
      if (nameSeen[name]) {
        nameSeen[name]++
        name = `${name}_${nameSeen[name]}`
      } else {
        nameSeen[name] = 1
      }

      // A trapped wasm instance stays broken, so no later cell's result can be trusted
      if (globalThis.__allWasmTrap) throw new Error(`not run: wasm trapped in ${globalThis.__allWasmTrap}`)

      const mod = require(url)
      const fn = (mod && mod.main) || (typeof mod === 'function' ? mod : null)
      if (typeof fn === 'function') {
        // For hierarchical models: pass child proxy
        // For legacy models: wrapLegacyModule detects child proxy and creates isolated state
        const geoms = [].concat(fn(params[name])).flat()
        all.push(...normalizeAndPlace(geoms, x, y, cellSize))
      }
    } catch (err) {
      // One bad model marks its own cell; the rest of the grid still renders
      if (isWasmTrap(err)) globalThis.__allWasmTrap ??= url
      console.error(`ALL: FAILED ${url}: ${err.message}`)
      failed.push(url)
      try {
        all.push(...normalizeAndPlace(failureMarker(), x, y, cellSize))
      } catch { /* the marker needs the same wasm */ }
    }
  })

  if (failed.length) {
    console.error(`ALL: ${failed.length}/${items.length} models failed: ${failed.join(' ')}`)
  }
  return all
}

module.exports = { main }
