"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script – loads each model under its own params namespace,
// normalises it to the grid cell size, and positions it in a grid.
const { gridPosition, normalizeAndPlace, urlToPartName } = require('../../../lib/grid-utils.js')

const items = [
  "./bosl-arc-of.scad",
  "./bosl-bottom-half.scad",
  "./bosl-distribute.scad",
  "./bosl-grid2d.scad",
  "./bosl-grid3d.scad",
  "./bosl-half-of.scad",
  "./bosl-left-half.scad",
  "./bosl-mirror-copy.scad",
  "./bosl-right-half.scad",
  "./bosl-rot-copies.scad",
  "./bosl-top-half.scad",
  "./bosl-xdistribute.scad",
  "./bosl-xflip-copy.scad",
  "./bosl-xring.scad",
  "./bosl-xrot-copies.scad",
  "./bosl-ydistribute.scad",
  "./bosl-yflip-copy.scad",
  "./bosl-yring.scad",
  "./bosl-yrot-copies.scad",
  "./bosl-zdistribute.scad",
  "./bosl-zflip-copy.scad",
  "./bosl-zring.scad",
  "./bosl-zrot-copies.scad",
  "./bosl-zspread.scad"
]
const spacing = 60
const cellSize = 51

const main = (params) => {
  const all = []
  const nameSeen = {}

  items.forEach((url, i) => {
    try {
      // Calculate grid position dynamically
      const [x, y] = gridPosition(i, items.length, spacing)

      // Derive unique part name from URL
      let name = urlToPartName(url)
      // Deduplicate: if the same name appears twice, append _2, _3, …
      if (nameSeen[name]) {
        nameSeen[name]++
        name = `${name}_${nameSeen[name]}`
      } else {
        nameSeen[name] = 1
      }

      const mod = require(url)
      const fn = (mod && mod.main) || (typeof mod === 'function' ? mod : null)
      if (typeof fn === 'function') {
        // For hierarchical models: pass child proxy
        // For legacy models: wrapLegacyModule detects child proxy and creates isolated state
        const geoms = [].concat(fn(params[name]))
        all.push(...normalizeAndPlace(geoms, x, y, cellSize))
      }
    } catch (err) {
      console.error('ALL: failed to load', url, err.message)
      throw new Error(`Failed to load ${url}: ${err.message}`)
    }
  })
  return all
}

module.exports = { main }
