"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../lib/grid-utils.js')

const items = [
  "./complex-csg.scad",
  "./crystal.scad",
  "./cube-centered.scad",
  "./cube.scad",
  "./cylinder.scad",
  "./difference.scad",
  "./flag-italy.scad",
  "./hull-2d.scad",
  "./hull-3d.scad",
  "./intersection.scad",
  "./linear-extrude.scad",
  "./mirror.scad",
  "./polygon.scad",
  "./preview-gate.scad",
  "./rotate-extrude.scad",
  "./rotate.scad",
  "./scale.scad",
  "./sphere.scad",
  "./union.scad",
  "./use-statement.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
