"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../lib/grid-utils.js')

const items = [
  "./070-shapes-corrugated_wall.scad",
  "./071-shapes-pie_slice.scad",
  "./072-shapes-interior_fillet.scad",
  "./073-shapes-slot.scad",
  "./074-shapes-arced_slot.scad",
  "./075-sliders-slider.scad",
  "./076-sliders-rail.scad",
  "./077-threading-trapezoidal_threaded_nut.scad",
  "./078-threading-threaded_rod.scad",
  "./079-threading-threaded_nut.scad",
  "./080-threading-buttress_threaded_rod.scad",
  "./081-threading-buttress_threaded_nut.scad",
  "./082-threading-metric_trapezoidal_threaded_rod.scad",
  "./083-threading-metric_trapezoidal_threaded_nut.scad",
  "./084-threading-acme_threaded_rod.scad",
  "./085-threading-acme_threaded_nut.scad",
  "./086-threading-square_threaded_rod.scad",
  "./087-threading-square_threaded_nut.scad",
  "./088-torx_drive-torx_drive.scad",
  "./089-transforms-unknown.scad",
  "./090-transforms-xscale.scad",
  "./091-transforms-yscale.scad",
  "./092-transforms-zscale.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
