"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../lib/grid-utils.js')

const items = [
  "./001-attachments-cuboid.scad",
  "./002-attachments-prismoid.scad",
  "./003-attachments-cyl.scad",
  "./004-attachments-spheroid.scad",
  "./005-attachments-anchor_arrow.scad",
  "./006-attachments-anchor_arrow2d.scad",
  "./007-attachments-generic_airplane.scad",
  "./008-attachments-frame_ref.scad",
  "./009-ball_bearings-ball_bearing.scad",
  "./010-bottlecaps-pco1810_neck.scad",
  "./011-bottlecaps-expose_anchors.scad",
  "./012-bottlecaps-pco1810_cap.scad",
  "./013-bottlecaps-pco1881_neck.scad",
  "./014-bottlecaps-pco1881_cap.scad",
  "./015-bottlecaps-generic_bottle_neck.scad",
  "./016-bottlecaps-generic_bottle_cap.scad",
  "./017-bottlecaps-bottle_adapter_neck_to_cap.scad",
  "./018-bottlecaps-bottle_adapter_cap_to_cap.scad",
  "./019-bottlecaps-bottle_adapter_neck_to_neck.scad",
  "./020-color-highlight.scad",
  "./021-color-highlight_this.scad",
  "./022-color-ghost.scad",
  "./023-color-ghost_this.scad",
  "./024-color-hsl.scad",
  "./025-color-hsv.scad",
  "./026-comparisons-max_index.scad",
  "./027-constants-cube.scad",
  "./028-constants-cuboid.scad",
  "./029-cubetruss-cubetruss_foot.scad",
  "./030-cubetruss-cubetruss_joiner.scad",
  "./031-cubetruss-cubetruss_uclip.scad",
  "./032-cubetruss-cubetruss_clip.scad",
  "./033-distributors-xcopies.scad",
  "./034-distributors-ycopies.scad",
  "./035-distributors-zcopies.scad",
  "./036-distributors-grid_copies.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
