"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../lib/grid-utils.js')

const items = [
  "./093-transforms-xflip.scad",
  "./094-transforms-yflip.scad",
  "./095-transforms-zflip.scad",
  "./096-transforms-grid3d.scad",
  "./097-transforms-rot_copies.scad",
  "./098-transforms-xrot_copies.scad",
  "./099-transforms-yrot_copies.scad",
  "./100-transforms-zrot_copies.scad",
  "./101-transforms-xring.scad",
  "./102-transforms-yring.scad",
  "./103-transforms-zring.scad",
  "./104-transforms-ovoid_spread.scad",
  "./105-transforms-mirror_copy.scad",
  "./106-transforms-xflip_copy.scad",
  "./107-transforms-yflip_copy.scad",
  "./108-transforms-zflip_copy.scad",
  "./109-transforms-half_of.scad",
  "./110-wiring-hex_offset_ring.scad",
  "./111-wiring-wiring.scad",
  "./bezier_patches.scad",
  "./orientations.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
