"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../../lib/grid-utils.js')

const items = [
  "./fern_leaf_stencil.scad",
  "./forest.scad",
  "./hilbert_curve_drawing.scad",
  "./lsystem2_collection.scad",
  "./lsystem3_collection.scad",
  "./sierpinski_triangle.scad",
  "./tree.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
