"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../lib/grid-utils.js')

const items = [
  "./073-linear_bearings-lmXuu_bearing.scad",
  "./074-lists-reverse.scad",
  "./075-masks-chamfer_edge_mask.scad",
  "./076-masks-polygon_edge_mask.scad",
  "./077-masks-chamfer_corner_mask.scad",
  "./078-masks-rounding_corner_mask.scad",
  "./079-masks-teardrop_corner_mask.scad",
  "./080-masks-rounding_hole_mask.scad",
  "./081-math-log2.scad",
  "./082-math-sum.scad",
  "./083-math-mean.scad",
  "./084-math-deltas.scad",
  "./085-math-product.scad",
  "./086-math-cumprod.scad",
  "./087-metric_screws-generic_screw.scad",
  "./088-metric_screws-metric_bolt.scad",
  "./089-metric_screws-metric_nut.scad",
  "./090-miscellaneous-path_extrude2d.scad",
  "./091-miscellaneous-cylindrical_extrude.scad",
  "./092-modular_hose-modular_hose.scad",
  "./093-modular_hose-cylinder.scad",
  "./094-modular_hose-cuboid.scad",
  "./095-nema_steppers-nema_mount_mask.scad",
  "./096-partitions-half_of.scad",
  "./097-partitions-left_half.scad",
  "./098-partitions-back_half.scad",
  "./099-partitions-bottom_half.scad",
  "./100-polyhedra-regular_polyhedron.scad",
  "./101-rounding-convex_offset_extrude.scad",
  "./102-rounding-rounded_prism.scad",
  "./103-rounding-bent_cutout_mask.scad",
  "./104-rounding-cuboid.scad",
  "./105-rounding-cyl.scad",
  "./106-rounding-sphere.scad",
  "./107-screw_drive-torx_mask.scad",
  "./108-screw_drive-robertson_mask.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
