"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../lib/grid-utils.js')

const items = [
  "./Coin_01.scad",
  "./Coin_02.scad",
  "./Cone_01.scad",
  "./Crystal.scad",
  "./Cup_01.scad",
  "./Display_Seven_Segments.scad",
  "./Door_01.scad",
  "./Electric_Wire_Plug.scad",
  "./Eyebolt.scad",
  "./Fence_01.scad",
  "./Fence_02.scad",
  "./Fireplace_01.scad",
  "./Flag_France.scad",
  "./Flag_Italy.scad",
  "./Flange_01.scad",
  "./Flange_02.scad",
  "./Flange_03.scad",
  "./Floor_01.scad",
  "./Gear_01.scad",
  "./Gear_02.scad",
  "./Grid_01.scad",
  "./Hexagon_socket_screw_keys.scad",
  "./Hole_Plate.scad",
  "./Ingot_01.scad",
  "./Key.scad",
  "./Key_Old_01.scad",
  "./Key_Simple.scad",
  "./Ladder_01.scad",
  "./Ladder_02.scad",
  "./Lamp_01.scad",
  "./Led_01.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
