"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../lib/grid-utils.js')

const items = [
  "./109-screws-shoulder_screw.scad",
  "./110-screws-nut.scad",
  "./111-screws-nut_trap_side.scad",
  "./112-screws-nut_trap_inline.scad",
  "./113-shapes2d-linear_extrude.scad",
  "./114-shapes3d-cube.scad",
  "./115-shapes3d-cuboid.scad",
  "./116-shapes3d-prismoid.scad",
  "./117-shapes3d-regular_prism.scad",
  "./118-shapes3d-rect_tube.scad",
  "./119-shapes3d-wedge.scad",
  "./120-shapes3d-octahedron.scad",
  "./121-shapes3d-cylinder.scad",
  "./122-shapes3d-cyl.scad",
  "./123-shapes3d-tube.scad",
  "./124-shapes3d-back_half.scad",
  "./125-shapes3d-pie_slice.scad",
  "./126-shapes3d-sphere.scad",
  "./127-shapes3d-spheroid.scad",
  "./128-shapes3d-color.scad",
  "./129-shapes3d-torus.scad",
  "./130-shapes3d-teardrop.scad",
  "./131-shapes3d-onion.scad",
  "./132-shapes3d-fillet.scad",
  "./133-skin-skin.scad",
  "./134-skin-linear_sweep.scad",
  "./135-sliders-slider.scad",
  "./136-sliders-rail.scad",
  "./137-strings-parse_num.scad",
  "./138-strings-format_float.scad",
  "./139-threading-acme_threaded_rod.scad",
  "./140-threading-acme_threaded_nut.scad",
  "./141-threading-buttress_threaded_rod.scad",
  "./142-threading-buttress_threaded_nut.scad",
  "./143-threading-square_threaded_rod.scad",
  "./144-threading-square_threaded_nut.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
