"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../../lib/grid-utils.js')

const items = [
  "./delaunay_fibonacci.scad",
  "./ripple_sphere.scad",
  "./ripple_vase.scad",
  "./ripples.scad",
  "./rock_horn.scad",
  "./ruyi_pineapple.scad",
  "./voronoi_bracelet.scad",
  "./voronoi_crystallization.scad",
  "./voronoi_fibonacci.scad",
  "./voronoi_fibonacci2.scad",
  "./voronoi_holder.scad",
  "./voronoi_penholder.scad",
  "./voronoi_sphere.scad",
  "./voronoi_torus.scad",
  "./voronoi_vase.scad",
  "./worley_vase.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
