export const examples = [
  { name: 'Two Cars', source: './examples/two-cars.example.js' },
  { name: 'Hierarchical Car', source: './examples/hierarchical-car.example.js' },
  { name: 'JSCAD Logo', source: './examples/jscad.example.js' },
  { name: 'Primitive Shapes', source: './examples/primitives.example.js' },
  { name: 'Extrusions', source: './examples/extrusions.example.js' },
  { name: 'Hull Operations', source: './examples/hulls.example.js' },
  { name: 'Parametric Gear', source: './examples/gear.example.js' },
  { name: 'Nuts and Bolts', source: './examples/nuts-and-bolts.example.js' },
  { name: 'Text Shapes', source: './examples/text.example.js' },
  { name: 'Slicer', source: './examples/slicer.example.js' },
  { name: 'Balloons', source: './examples/balloons.example.js' },
  { name: 'Parameter Types', source: './examples/parameters.example.js' },
  { name: 'Multipart project', source: './examples/multipart.example.js' },
  { name: 'Import AMF', source: './examples/14-AMFImport/index.js' },
  { name: 'Import STL', source: './examples/15-STLImport/index.js' },
  { name: 'Import SVG', source: './examples/16-SVGImport/index.js' },
  { name: 'Test SVG before Extrude', source: './examples/svg-tester.js' },
  // Benchmarks - stress tests for CSG performance
  { name: 'Benchmark: Menger Sponge', source: './examples/benchmarks/menger.example.js' },
  { name: 'Benchmark: Menger Intersect', source: './examples/benchmarks/menger-intersect.example.js' },
  { name: 'Benchmark: Swiss Cheese', source: './examples/benchmarks/swiss-cheese.example.js' },
  { name: 'Benchmark: Thin Wall', source: './examples/benchmarks/thin-wall.example.js' },
  { name: 'Benchmark: Sphere Cloud', source: './examples/benchmarks/sphere-cloud.example.js' },
  { name: 'Benchmark: Sphere Union', source: './examples/benchmarks/sphere-union.example.js' },
  { name: 'Benchmark: Chainmail', source: './examples/benchmarks/chainmail.example.js' },
  { name: 'Benchmark: Hull', source: './examples/benchmarks/hull.example.js' },
  { name: 'Benchmark: Hull Chain', source: './examples/benchmarks/hull-chain.example.js' },
  { name: 'Benchmark: Mounting Plate', source: './examples/benchmarks/mounting-plate.example.js' },
  { name: 'Benchmark: Expand', source: './examples/benchmarks/expand.example.js' },
  { name: 'Benchmark: Vase (Lathe)', source: './examples/benchmarks/vase.example.js' },
  { name: 'Benchmark: Minkowski Sum', source: './examples/benchmarks/minkowski.example.js' },
  { name: 'Benchmark: Minkowski Frame', source: './examples/benchmarks/minkowski-frame.example.js' },
]
