export const examples = [
  { name: 'Two Cars', source: './examples/01-two-cars.example.js' },
  { name: 'Hierarchical Car', source: './examples/02-hierarchical-car.example.js' },
  { name: 'JSCAD Logo', source: './examples/03-jscad.example.js' },
  { name: 'Primitive Shapes', source: './examples/04-primitives.example.js' },
  { name: 'Extrusions', source: './examples/05-extrusions.example.js' },
  { name: 'Hull Operations', source: './examples/06-hulls.example.js' },
  { name: 'Parametric Gear', source: './examples/07-gear.example.js' },
  { name: 'Nuts and Bolts', source: './examples/08-nuts-and-bolts.example.js' },
  { name: 'Text Shapes', source: './examples/09-text.example.js' },
  { name: 'Slicer', source: './examples/10-slicer.example.js' },
  { name: 'Balloons', source: './examples/11-balloons.example.js' },
  { name: 'Parameter Types', source: './examples/12-parameters.example.js' },
  { name: 'Multipart project', source: './examples/13-multipart.example.js' },
  { name: 'Import AMF', source: './examples/14-AMFImport/index.js' },
  { name: 'Import STL', source: './examples/15-STLImport/index.js' },
  { name: 'Import SVG', source: './examples/16-SVGImport/index.js' },
  { name: 'Test SVG before Extrude', source: './examples/17-svg-tester.js' },
  // Benchmarks - stress tests for CSG performance
  { name: 'Benchmark: Menger Sponge', source: './examples/benchmarks/01-menger.example.js' },
  { name: 'Benchmark: Menger Intersect', source: './examples/benchmarks/02-menger-intersect.example.js' },
  { name: 'Benchmark: Swiss Cheese', source: './examples/benchmarks/03-swiss-cheese.example.js' },
  { name: 'Benchmark: Thin Wall', source: './examples/benchmarks/04-thin-wall.example.js' },
  { name: 'Benchmark: Sphere Cloud', source: './examples/benchmarks/05-sphere-cloud.example.js' },
  { name: 'Benchmark: Sphere Union', source: './examples/benchmarks/06-sphere-union.example.js' },
  { name: 'Benchmark: Chainmail', source: './examples/benchmarks/07-chainmail.example.js' },
  { name: 'Benchmark: Hull', source: './examples/benchmarks/08-hull.example.js' },
  { name: 'Benchmark: Hull Chain', source: './examples/benchmarks/09-hull-chain.example.js' },
  { name: 'Benchmark: Mounting Plate', source: './examples/benchmarks/10-mounting-plate.example.js' },
  { name: 'Benchmark: Expand', source: './examples/benchmarks/11-expand.example.js' },
  { name: 'Benchmark: Vase (Lathe)', source: './examples/benchmarks/12-vase.example.js' },
  { name: 'Benchmark: Minkowski Sum', source: './examples/benchmarks/13-minkowski.example.js' },
  { name: 'Benchmark: Minkowski Frame', source: './examples/benchmarks/14-minkowski-frame.example.js' },
]
