export const examples = [
  { name: 'Two Cars', source: './examples/two-cars.example.js' },
  { name: 'Hierarchical Car', source: './examples/hierarchical-car.example.js' },
  { name: 'JSCAD Logo', source: './examples/jscad.example.js' },
  { name: 'Primitive Shapes', source: './examples/primitives.example.js' },
  { name: 'Extrusions', source: './examples/extrusions.example.js' },
  { name: 'Hull Operations', source: './examples/hulls.example.js' },
  { name: 'Parametric Gear', source: './examples/gear.example.js' },
  { name: 'Nuts and Bolts', source: './examples/nuts-and-bolts.example.js' },
  { name: 'Text Shapes', source: './examples/text.example.js' },
  { name: 'Slicer', source: './examples/slicer.example.js' },
  { name: 'Balloons', source: './examples/balloons.example.js' },
  { name: 'Parameter Types', source: './examples/parameters.example.js' },
  { name: 'Multipart project', source: './examples/multipart.project.template.js' },
  { name: 'Import AMF', source: './examples/AMFImport/index.js' },
  { name: 'Import STL', source: './examples/STLImport/index.js' },
  { name: 'Import SVG', source: './examples/SVGImport/index.js' },
  { name: 'Test SVG before Etrude', source: './examples/svg.tester.js' },
  // Benchmarks - stress tests for CSG performance
  { name: 'Benchmark: Menger Sponge', source: './examples/benchmark-menger.example.js' },
  { name: 'Benchmark: Menger Intersect', source: './examples/benchmark-menger-intersect.example.js' },
  { name: 'Benchmark: Swiss Cheese', source: './examples/benchmark-swiss-cheese.example.js' },
  { name: 'Benchmark: Thin Wall', source: './examples/benchmark-thin-wall.example.js' },
  { name: 'Benchmark: Sphere Cloud', source: './examples/benchmark-sphere-cloud.example.js' },
  { name: 'Benchmark: Sphere Union', source: './examples/benchmark-sphere-union.example.js' },
  { name: 'Benchmark: Chainmail', source: './examples/benchmark-chainmail.example.js' },
  { name: 'Benchmark: Hull', source: './examples/benchmark-hull.example.js' },
  { name: 'Benchmark: Hull Chain', source: './examples/benchmark-hull-chain.example.js' },
  { name: 'Benchmark: Mounting Plate', source: './examples/benchmark-mounting-plate.example.js' },
  { name: 'Benchmark: Expand', source: './examples/benchmark-expand.example.js' },
  { name: 'Benchmark: Vase (Lathe)', source: './examples/benchmark-vase.example.js' },
  { name: 'Benchmark: Minkowski Sum', source: './examples/benchmark-minkowski.example.js' },
  { name: 'Benchmark: Minkowski Frame', source: './examples/benchmark-minkowski-frame.example.js' },
]
