"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../../lib/grid-utils.js')

const items = [
  "./hollow_out_cylinder.scad",
  "./hollow_out_holder.scad",
  "./hollow_out_square.scad",
  "./hollow_out_starburst.scad",
  "./hollow_out_torus.scad",
  "./hollow_out_vase.scad",
  "./hollow_torus_knot.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
