"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script – loads each model under its own params namespace,
// normalises it to the grid cell size, and positions it in a grid.
const { gridPosition, normalizeAndPlace, urlToPartName, failureMarker } = require('../../../lib/grid-utils.js')

const items = [
  "./bearing_captured_in_mobius_cut.scad",
  "./bunny_frame.scad",
  "./cat_corner_protector.scad",
  "./caterpillar.scad",
  "./chrome_dino.scad",
  "./curved_cabinet.scad",
  "./dancing_cubes.scad",
  "./daruma.scad",
  "./distorted_vase.scad",
  "./dot_photo_sphere.scad",
  "./drilled_cube.scad",
  "./emoticon_moai.scad",
  "./emotion_ball.scad",
  "./fidget_ball.scad",
  "./fourier_vase.scad",
  "./hypnotic_squares.scad",
  "./image_slicer.scad",
  "./klein_bottle.scad",
  "./knot.scad",
  "./mandelbrot_set.scad",
  "./mask_hook.scad",
  "./melted_clock.scad",
  "./mobius_twins.scad",
  "./ms_clippy.scad",
  "./multiplication_puzzle..scad",
  "./owl.scad",
  "./perlin_noise_cylinder.scad",
  "./photo_fibonacci_lattice.scad",
  "./photo_sphere.scad",
  "./platonic_solid_wireframe.scad",
  "./qr_coder.scad",
  "./rubber_duck_debugging.scad",
  "./samurai_daruma.scad",
  "./shape2wire.scad",
  "./sierpinski_pyramid.scad",
  "./superformula_vase.scad",
  "./tableware_organizer.scad",
  "./taiji.scad",
  "./tetrapod_doll.scad",
  "./text_box.scad",
  "./trefoil_klein_bottle.scad",
  "./triangle_splice.scad",
  "./twisted_ring.scad",
  "./vampire_pen_holder.scad",
  "./voxel_vase.scad",
  "./walk_torus83_fort.scad",
  "./worley_noise_ball.scad",
  "./wormhole.scad",
  "./circle_packing/ALL.js",
  "./dragon/ALL.js",
  "./floor_stand/ALL.js",
  "./hollow_out/ALL.js",
  "./maze/ALL.js",
  "./soccer_polyhedron/ALL.js",
  "./spiral/ALL.js",
  "./spiral_polygons/ALL.js",
  "./stereographic_projection/ALL.js",
  "./taiwan/ALL.js",
  "./tiles/ALL.js",
  "./triangle2square/ALL.js",
  "./turtle/ALL.js",
  "./voronoi/ALL.js"
]
const spacing = 60
const cellSize = 51

const isWasmTrap = (err) =>
  (typeof WebAssembly !== 'undefined' && err instanceof WebAssembly.RuntimeError) || err?.name === 'RuntimeError'

const main = (params) => {
  const all = []
  const nameSeen = {}
  const failed = []

  items.forEach((url, i) => {
    // Calculate grid position dynamically
    const [x, y] = gridPosition(i, items.length, spacing)

    try {
      // Derive unique part name from URL
      let name = urlToPartName(url)
      // Deduplicate: if the same name appears twice, append _2, _3, …
      if (nameSeen[name]) {
        nameSeen[name]++
        name = `${name}_${nameSeen[name]}`
      } else {
        nameSeen[name] = 1
      }

      // A trapped wasm instance stays broken, so no later cell's result can be trusted
      if (globalThis.__allWasmTrap) throw new Error(`not run: wasm trapped in ${globalThis.__allWasmTrap}`)

      const mod = require(url)
      const fn = (mod && mod.main) || (typeof mod === 'function' ? mod : null)
      if (typeof fn === 'function') {
        // For hierarchical models: pass child proxy
        // For legacy models: wrapLegacyModule detects child proxy and creates isolated state
        const geoms = [].concat(fn(params[name])).flat()
        all.push(...normalizeAndPlace(geoms, x, y, cellSize))
      }
    } catch (err) {
      // One bad model marks its own cell; the rest of the grid still renders
      if (isWasmTrap(err)) globalThis.__allWasmTrap ??= url
      console.error(`ALL: FAILED ${url}: ${err.message}`)
      failed.push(url)
      try {
        all.push(...normalizeAndPlace(failureMarker(), x, y, cellSize))
      } catch { /* the marker needs the same wasm */ }
    }
  })

  if (failed.length) {
    console.error(`ALL: ${failed.length}/${items.length} models failed: ${failed.join(' ')}`)
  }
  return all
}

module.exports = { main }
