import { writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { fluentEntries } from './fluent.js'
import { jscadTextEntries, modelingEntries } from './jsdocEntries.js'
import { isMainModule } from '../src/mainModule.js'

const require = createRequire(import.meta.url)

// Functions that hand their own options object to another public function.
const PASS_THROUGH = {
  'extrusions.extrudeRectangular': ['expansions.expand', 'extrusions.extrudeLinear'],
}

const addPassThrough = (entries) => {
  const byName = new Map(entries.map((e) => [e.name, e]))
  for (const [name, targets] of Object.entries(PASS_THROUGH)) {
    const entry = byName.get(name)
    for (const target of targets) {
      for (const option of byName.get(target).options ?? []) {
        if (!entry.options.some((o) => o.name === option.name)) entry.options.push(option)
      }
    }
  }
  return entries
}

export const buildIndex = () => {
  const modeling = addPassThrough(modelingEntries(dirname(require.resolve('@jscad/modeling'))))
  const fluent = fluentEntries(dirname(require.resolve('@jbroll/jscad-fluent')), modeling)
  const text = jscadTextEntries(fileURLToPath(new URL('../../jscad-text/src', import.meta.url)))
  return [...modeling, ...fluent, ...text]
}

const PACKAGE_PREFIX = { '@jscad/modeling': '', '@jbroll/jscad-fluent': 'jf.' }

const optionNames = (e, byName) => ((e.sameAs ? byName.get(e.sameAs) : e).options ?? []).map((o) => o.name).sort()

export const optionTables = (entries) => {
  const byName = new Map(entries.map((e) => [e.name, e]))
  const classes = new Set(entries.filter((e) => e.kind === 'class').map((e) => e.name))
  const tables = {}
  for (const [pkg, prefix] of Object.entries(PACKAGE_PREFIX)) {
    const options = {}
    const methods = {}
    for (const e of entries) {
      if (e.pkg !== pkg || !e.optionsFirst) continue
      const dot = e.name.indexOf('.')
      const owner = e.name.slice(0, dot)
      if (classes.has(owner)) {
        methods[owner] ??= {}
        methods[owner][e.name.slice(dot + 1)] = optionNames(e, byName)
      } else if (e.name.startsWith(prefix)) {
        options[e.name.slice(prefix.length)] = optionNames(e, byName)
      }
    }
    tables[pkg] = { prefix, options, methods }
  }
  return tables
}

export const formatIndex = (entries) => `[\n${entries.map((e) => JSON.stringify(e)).join(',\n')}\n]\n`

const rows = (record, indent) => Object.entries(record).map(([key, names]) => `${indent}${JSON.stringify(key)}: ${JSON.stringify(names)},`)

export const formatOptionTable = (tables) => {
  const packages = Object.entries(tables).map(([pkg, { prefix, options, methods }]) => {
    const classes = Object.entries(methods).map(([cls, byMethod]) => `      ${JSON.stringify(cls)}: {\n${rows(byMethod, '        ').join('\n')}\n      },`)
    const methodBlock = classes.length ? `{\n${classes.join('\n')}\n    }` : '{}'
    return `  ${JSON.stringify(pkg)}: {\n    prefix: ${JSON.stringify(prefix)},\n    options: {\n${rows(options, '      ').join('\n')}\n    },\n    methods: ${methodBlock},\n  },`
  })
  return `// Generated by api/build-index.js; do not edit. Run: npm run api-index -w @jscadui/agent-loop\nexport const OPTION_TABLES = {\n${packages.join('\n')}\n}\n`
}

if (isMainModule(process.argv[1], import.meta.url)) {
  const entries = buildIndex()
  writeFileSync(new URL('./index.json', import.meta.url), formatIndex(entries))
  writeFileSync(new URL('./optionTable.js', import.meta.url), formatOptionTable(optionTables(entries)))
  console.log(`api-index: ${entries.length} entries`)
}
