import { writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { jscadTextEntries, modelingEntries } from './jsdocEntries.js'

const require = createRequire(import.meta.url)

// Functions that hand their own options object to another public function.
const PASS_THROUGH = {
  'extrusions.extrudeRectangular': ['expansions.expand', 'extrusions.extrudeLinear'],
}

const addPassThrough = (entries) => {
  const byName = new Map(entries.map((e) => [e.name, e]))
  for (const [name, targets] of Object.entries(PASS_THROUGH)) {
    const entry = byName.get(name)
    for (const target of targets) {
      for (const option of byName.get(target).options ?? []) {
        if (!entry.options.some((o) => o.name === option.name)) entry.options.push(option)
      }
    }
  }
  return entries
}

export const buildIndex = () => {
  const modeling = addPassThrough(modelingEntries(dirname(require.resolve('@jscad/modeling'))))
  const text = jscadTextEntries(fileURLToPath(new URL('../../jscad-text/src', import.meta.url)))
  return [...modeling, ...text]
}

const PACKAGE_PREFIX = { '@jscad/modeling': '', '@jbroll/jscad-fluent': 'jf.' }

export const optionTables = (entries) => {
  const byName = new Map(entries.map((e) => [e.name, e]))
  const tables = {}
  for (const [pkg, prefix] of Object.entries(PACKAGE_PREFIX)) {
    const options = {}
    for (const e of entries) {
      if (e.pkg !== pkg || !e.optionsFirst || !e.name.startsWith(prefix)) continue
      const source = e.sameAs ? byName.get(e.sameAs) : e
      options[e.name.slice(prefix.length)] = (source.options ?? []).map((o) => o.name).sort()
    }
    tables[pkg] = { prefix, options }
  }
  return tables
}

export const formatIndex = (entries) => `[\n${entries.map((e) => JSON.stringify(e)).join(',\n')}\n]\n`

export const formatOptionTable = (tables) => {
  const packages = Object.entries(tables).map(([pkg, { prefix, options }]) => {
    const rows = Object.entries(options).map(([path, names]) => `      ${JSON.stringify(path)}: ${JSON.stringify(names)},`)
    return `  ${JSON.stringify(pkg)}: {\n    prefix: ${JSON.stringify(prefix)},\n    options: {\n${rows.join('\n')}\n    },\n  },`
  })
  return `// Generated by api/build-index.js; do not edit. Run: npm run api-index -w @jscadui/agent-loop\nexport const OPTION_TABLES = {\n${packages.join('\n')}\n}\n`
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const entries = buildIndex()
  writeFileSync(new URL('./index.json', import.meta.url), formatIndex(entries))
  writeFileSync(new URL('./optionTable.js', import.meta.url), formatOptionTable(optionTables(entries)))
  console.log(`api-index: ${entries.length} entries`)
}
