"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script – loads each model under its own params namespace,
// normalises it to the grid cell size, and positions it in a grid.
const { gridPosition, normalizeAndPlace, urlToPartName } = require('../../../lib/grid-utils.js')

const items = [
  "./acme-threaded-nut.scad",
  "./acme-threaded-rod.scad",
  "./bosl-place-copies.scad",
  "./bosl-right-half.scad",
  "./bosl-rot-copies.scad",
  "./bosl-rot.scad",
  "./bosl-skew-xy.scad",
  "./bosl-skew-xz.scad",
  "./bosl-skew-yz.scad",
  "./bosl-spread.scad",
  "./bosl-top-half.scad",
  "./bosl-translate-copies.scad",
  "./bosl-up.scad",
  "./bosl-xdistribute.scad",
  "./bosl-xflip-copy.scad",
  "./bosl-xflip.scad",
  "./bosl-xring.scad",
  "./bosl-xrot-copies.scad",
  "./bosl-xrot.scad",
  "./bosl-xscale.scad",
  "./bosl-xspread.scad",
  "./bosl-ydistribute.scad",
  "./bosl-yflip-copy.scad",
  "./bosl-yflip.scad",
  "./bosl-yring.scad",
  "./bosl-yrot-copies.scad",
  "./bosl-yrot.scad",
  "./bosl-yscale.scad",
  "./bosl-yspread.scad",
  "./bosl-zdistribute.scad",
  "./bosl-zflip-copy.scad",
  "./bosl-zflip.scad",
  "./bosl-zring.scad",
  "./bosl-zrot-copies.scad",
  "./bosl-zrot.scad",
  "./bosl-zscale.scad",
  "./bosl-zspread.scad",
  "./buttress-threaded-rod.scad",
  "./chamfcube.scad",
  "./chamfer-cylinder-mask.scad",
  "./chamfer-hole-mask.scad",
  "./chamfer-mask-xyz.scad",
  "./chamfer-mask.scad",
  "./chamfer-modifier.scad",
  "./cyl-chamfer.scad",
  "./cyl.scad",
  "./cylinder-mask-fillet.scad",
  "./cylinder-mask.scad",
  "./diff-wrap.scad",
  "./directional-cubes.scad",
  "./extrude-from-to-twist.scad",
  "./extrude-from-to.scad",
  "./fillet-angled-corner-mask.scad",
  "./fillet-angled-edge-mask.scad",
  "./fillet-corner-mask.scad",
  "./fillet-cylinder-mask.scad",
  "./fillet-hole-mask.scad",
  "./fillet-mask-xyz.scad",
  "./fillet-mask.scad",
  "./fillet-modifier.scad",
  "./fwd-back.scad",
  "./grid2d.scad",
  "./hull-pair.scad",
  "./interior-fillet.scad",
  "./left-right.scad",
  "./metric-trapezoidal-rod.scad",
  "./mirror-copy.scad",
  "./modulated-circle.scad",
  "./narrowing-strut.scad",
  "./nested-transforms.scad",
  "./nil-noop.scad",
  "./onion.scad",
  "./oriented-cyls.scad",
  "./pie-slice.scad",
  "./prismoid.scad",
  "./rcube.scad",
  "./right-triangle.scad",
  "./rotations.scad",
  "./rounded-rect.scad",
  "./simple-cuboid.scad",
  "./slot.scad",
  "./square-threaded-rod.scad",
  "./teardrop.scad",
  "./threaded-nut.scad",
  "./threaded-rod-bevel.scad",
  "./threaded-rod-left.scad",
  "./threaded-rod.scad",
  "./torus.scad",
  "./transforms.scad",
  "./trapezoidal-threaded-nut.scad",
  "./trapezoidal-threaded-rod.scad",
  "./tube.scad",
  "./up-transform.scad",
  "./up.scad",
  "./xspread.scad",
  "./zring.scad"
]
const spacing = 60
const cellSize = 51

const main = (params) => {
  const all = []
  const nameSeen = {}

  items.forEach((url, i) => {
    try {
      // Calculate grid position dynamically
      const [x, y] = gridPosition(i, items.length, spacing)

      // Derive unique part name from URL
      let name = urlToPartName(url)
      // Deduplicate: if the same name appears twice, append _2, _3, …
      if (nameSeen[name]) {
        nameSeen[name]++
        name = `${name}_${nameSeen[name]}`
      } else {
        nameSeen[name] = 1
      }

      const mod = require(url)
      const fn = (mod && mod.main) || (typeof mod === 'function' ? mod : null)
      if (typeof fn === 'function') {
        // For hierarchical models: pass child proxy
        // For legacy models: wrapLegacyModule detects child proxy and creates isolated state
        const geoms = [].concat(fn(params[name]))
        all.push(...normalizeAndPlace(geoms, x, y, cellSize))
      }
    } catch (err) {
      console.error('ALL: failed to load', url, err.message)
      throw new Error(`Failed to load ${url}: ${err.message}`)
    }
  })
  return all
}

module.exports = { main }
