"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script – loads each model under its own params namespace,
// normalises it to the grid cell size, and positions it in a grid.
const { gridPosition, normalizeAndPlace, urlToPartName, failureMarker } = require('../../../lib/grid-utils.js')

const items = [
  "./tests/ALL.js"
]
const spacing = 60
const cellSize = 51

const main = (params) => {
  const all = []
  const nameSeen = {}
  const failed = []

  items.forEach((url, i) => {
    // Calculate grid position dynamically
    const [x, y] = gridPosition(i, items.length, spacing)

    try {
      // Derive unique part name from URL
      let name = urlToPartName(url)
      // Deduplicate: if the same name appears twice, append _2, _3, …
      if (nameSeen[name]) {
        nameSeen[name]++
        name = `${name}_${nameSeen[name]}`
      } else {
        nameSeen[name] = 1
      }

      const mod = require(url)
      const fn = (mod && mod.main) || (typeof mod === 'function' ? mod : null)
      if (typeof fn === 'function') {
        // For hierarchical models: pass child proxy
        // For legacy models: wrapLegacyModule detects child proxy and creates isolated state
        const geoms = [].concat(fn(params[name])).flat()
        all.push(...normalizeAndPlace(geoms, x, y, cellSize))
      }
    } catch (err) {
      // One bad model marks its own cell; the rest of the grid still renders
      console.error(`ALL: FAILED ${url}: ${err.message}`)
      failed.push(url)
      all.push(...normalizeAndPlace(failureMarker(), x, y, cellSize))
    }
  })

  if (failed.length) {
    console.error(`ALL: ${failed.length}/${items.length} models failed: ${failed.join(' ')}`)
  }
  return all
}

module.exports = { main }
