"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../lib/grid-utils.js')

const items = [
  "./Abacus.scad",
  "./Angle Shelf.scad",
  "./Arc_01.scad",
  "./Arc_02.scad",
  "./Arrow_01.scad",
  "./Banner_01.scad",
  "./Base_cabinet_01.scad",
  "./Base_cabinet_02.scad",
  "./Beam_Angular.scad",
  "./Beam_C.scad",
  "./Beam_H.scad",
  "./Beam_T.scad",
  "./Bed_01.scad",
  "./Bed_02.scad",
  "./Bench_01.scad",
  "./Bench_02.scad",
  "./Bookshelf_01.scad",
  "./Bookshelf_02.scad",
  "./Box_Wood_01.scad",
  "./Bricks.scad",
  "./Building_01.scad",
  "./Building_02.scad",
  "./Chair_01.scad",
  "./Chair_02.scad",
  "./Chair_03.scad",
  "./Chalkboard_01.scad",
  "./Chalkboard_02.scad",
  "./Circular_Blade.scad",
  "./Gear_02.scad",
  "./Mechanism_01.scad",
  "./Spawing_Cube.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
