"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../lib/grid-utils.js')

const items = [
  "./01-basics/ALL.js",
  "./bosl/ALL.js",
  "./bosl2/ALL.js",
  "./dotscad/examples/ALL.js",
  "./mcad/examples/ALL.js",
  "./nopscadlib/NopSCADlib/tests/ALL.js",
  "./snippet/ALL.js",
  "./text/ALL.js"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
