"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script – loads each model under its own params namespace,
// normalises it to the grid cell size, and positions it in a grid.
const { gridPosition, normalizeAndPlace, urlToPartName } = require('../../../../lib/grid-utils.js')

const items = [
  "./cube_maze.scad",
  "./cylinder_maze.scad",
  "./devil_maze.scad",
  "./euler_maze.scad",
  "./giant_maze.scad",
  "./gyro_maze.scad",
  "./heart2heart_maze.scad",
  "./heart_maze.scad",
  "./island_maze.scad",
  "./maze3d.scad",
  "./maze3d_mickey.scad",
  "./maze3d_sphere.scad",
  "./maze_city.scad",
  "./maze_masking.scad",
  "./maze_maze.scad",
  "./maze_tower.scad",
  "./maze_vase.scad",
  "./maze_yinyan.scad",
  "./mobius_maze.scad",
  "./noisy_circle_maze.scad",
  "./pyramid_hex_maze.scad",
  "./pyramid_maze.scad",
  "./random_scala.scad",
  "./regular_polygon_maze.scad",
  "./senbon_torii.scad",
  "./sphere_maze.scad",
  "./spiral_maze.scad",
  "./square_maze.scad",
  "./step_pyramid_maze.scad",
  "./stereographic_hex_maze.scad",
  "./stereographic_square_maze.scad",
  "./theta_maze.scad",
  "./torus_knot_maze.scad",
  "./torus_maze.scad",
  "./twisted_maze.scad"
]
const spacing = 60
const cellSize = 51

const main = (params) => {
  const all = []
  const nameSeen = {}

  items.forEach((url, i) => {
    try {
      // Calculate grid position dynamically
      const [x, y] = gridPosition(i, items.length, spacing)

      // Derive unique part name from URL
      let name = urlToPartName(url)
      // Deduplicate: if the same name appears twice, append _2, _3, …
      if (nameSeen[name]) {
        nameSeen[name]++
        name = `${name}_${nameSeen[name]}`
      } else {
        nameSeen[name] = 1
      }

      // Isolate each model from the previous one's shared-worker state
      // ($fn scope, transpiler include cache) so grid neighbours don't collide.
      if (typeof __resetScadGridItem === 'function') __resetScadGridItem()
      const mod = require(url)
      const fn = (mod && mod.main) || (typeof mod === 'function' ? mod : null)
      if (typeof fn === 'function') {
        // For hierarchical models: pass child proxy
        // For legacy models: wrapLegacyModule detects child proxy and creates isolated state
        const geoms = [].concat(fn(params[name])).flat()
        all.push(...normalizeAndPlace(geoms, x, y, cellSize))
      }
    } catch (err) {
      console.error('ALL: failed to load', url, err.message)
      throw new Error(`Failed to load ${url}: ${err.message}`)
    }
  })
  return all
}

module.exports = { main }
