"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../../lib/grid-utils.js')

const items = [
  "./cube_maze.scad",
  "./cylinder_maze.scad",
  "./devil_maze.scad",
  "./euler_maze.scad",
  "./giant_maze.scad",
  "./gyro_maze.scad",
  "./heart2heart_maze.scad",
  "./heart_maze.scad",
  "./island_maze.scad",
  "./maze3d.scad",
  "./maze3d_mickey.scad",
  "./maze3d_sphere.scad",
  "./maze_city.scad",
  "./maze_masking.scad",
  "./maze_maze.scad",
  "./maze_tower.scad",
  "./maze_vase.scad",
  "./maze_yinyan.scad",
  "./mobius_maze.scad",
  "./noisy_circle_maze.scad",
  "./pyramid_hex_maze.scad",
  "./pyramid_maze.scad",
  "./random_scala.scad",
  "./regular_polygon_maze.scad",
  "./rock_theta_maze.scad",
  "./senbon_torii.scad",
  "./sphere_maze.scad",
  "./spiral_maze.scad",
  "./square_maze.scad",
  "./step_pyramid_maze.scad",
  "./stereographic_hex_maze.scad",
  "./stereographic_square_maze.scad",
  "./theta_maze.scad",
  "./torus_knot_maze.scad",
  "./torus_maze.scad",
  "./twisted_maze.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
