"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script – loads each model under its own params namespace,
// normalises it to the grid cell size, and positions it in a grid.
const { gridPosition, normalizeAndPlace, urlToPartName } = require('../../../lib/grid-utils.js')

const items = [
  "./attachments-ex.scad",
  "./ball_bearings-ex.scad",
  "./bottlecaps-ex.scad",
  "./color-ex.scad",
  "./constants-ex.scad",
  "./cubetruss-ex.scad",
  "./distributors-ex.scad",
  "./drawing-ex.scad",
  "./gears-ex.scad",
  "./geometry-ex.scad",
  "./glued-circles.scad",
  "./grid-copies.scad",
  "./hexagon.scad",
  "./hinges-ex.scad",
  "./intersect.scad",
  "./joiners-ex.scad",
  "./keyhole.scad",
  "./left-right.scad",
  "./line-copies.scad",
  "./linear-sweep.scad",
  "./linear_bearings-ex.scad",
  "./mask2d-chamfer.scad",
  "./mask2d-roundover.scad",
  "./masks-ex.scad",
  "./metric_screws-ex.scad",
  "./mirror-copy.scad",
  "./miscellaneous-ex.scad",
  "./modular_hose-ex.scad",
  "./move.scad",
  "./nema_steppers-ex.scad",
  "./octagon.scad",
  "./octahedron.scad",
  "./offset-stroke.scad",
  "./offset-sweep.scad",
  "./onion.scad",
  "./partitions-ex.scad",
  "./path-sweep.scad",
  "./pentagon.scad",
  "./pie-slice.scad",
  "./polyhedra-ex.scad",
  "./position.scad",
  "./prismoid.scad",
  "./rect-chamfer.scad",
  "./rect-rounding.scad",
  "./rect-tube.scad",
  "./rect.scad",
  "./regular-ngon.scad",
  "./regular-prism.scad",
  "./reuleaux-polygon.scad",
  "./right-triangle.scad",
  "./ring.scad",
  "./rot-copies.scad",
  "./rot.scad",
  "./rotate-sweep.scad",
  "./rounded-prism.scad",
  "./rounding-corner-mask.scad",
  "./rounding-edge-mask.scad",
  "./rounding-ex.scad",
  "./scale.scad",
  "./screw_drive-ex.scad",
  "./screws-ex.scad",
  "./shapes2d-ex.scad",
  "./shapes3d-ex.scad",
  "./skew.scad",
  "./skin-ex.scad",
  "./skin.scad",
  "./sliders-ex.scad",
  "./sphere.scad",
  "./spheroid.scad",
  "./spiral-sweep.scad",
  "./square-anchor.scad",
  "./squircle.scad",
  "./star.scad",
  "./stroke.scad",
  "./supershape.scad",
  "./teardrop.scad",
  "./teardrop2d.scad",
  "./threading-ex.scad",
  "./tilt.scad",
  "./transforms-ex.scad",
  "./trapezoid.scad",
  "./tripod_mounts-ex.scad",
  "./walls-ex.scad",
  "./wiring-ex.scad"
]
const spacing = 60
const cellSize = 51

const main = (params) => {
  const all = []
  const nameSeen = {}

  items.forEach((url, i) => {
    try {
      // Calculate grid position dynamically
      const [x, y] = gridPosition(i, items.length, spacing)

      // Derive unique part name from URL
      let name = urlToPartName(url)
      // Deduplicate: if the same name appears twice, append _2, _3, …
      if (nameSeen[name]) {
        nameSeen[name]++
        name = `${name}_${nameSeen[name]}`
      } else {
        nameSeen[name] = 1
      }

      const mod = require(url)
      const fn = (mod && mod.main) || (typeof mod === 'function' ? mod : null)
      if (typeof fn === 'function') {
        // For hierarchical models: pass child proxy
        // For legacy models: wrapLegacyModule detects child proxy and creates isolated state
        const geoms = [].concat(fn(params[name])).flat()
        all.push(...normalizeAndPlace(geoms, x, y, cellSize))
      }
    } catch (err) {
      console.error('ALL: failed to load', url, err.message)
      throw new Error(`Failed to load ${url}: ${err.message}`)
    }
  })
  return all
}

module.exports = { main }
