"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../lib/grid-utils.js')

const items = [
  "./047-shapes-cuboid.scad",
  "./048-shapes-span_cube.scad",
  "./049-shapes-leftcube.scad",
  "./050-shapes-rightcube.scad",
  "./051-shapes-fwdcube.scad",
  "./052-shapes-backcube.scad",
  "./053-shapes-downcube.scad",
  "./054-shapes-upcube.scad",
  "./055-shapes-prismoid.scad",
  "./056-shapes-rounded_prismoid.scad",
  "./057-shapes-right_triangle.scad",
  "./058-shapes-cyl.scad",
  "./059-shapes-downcyl.scad",
  "./060-shapes-tube.scad",
  "./061-shapes-staggered_sphere.scad",
  "./062-shapes-teardrop.scad",
  "./063-shapes-onion.scad",
  "./064-shapes-narrowing_strut.scad",
  "./065-shapes-thinning_wall.scad",
  "./066-shapes-braced_thinning_wall.scad",
  "./067-shapes-thinning_triangle.scad",
  "./068-shapes-sparse_strut.scad",
  "./069-shapes-sparse_strut3d.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
