"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../lib/grid-utils.js')

const items = [
  "./037-distributors-rot_copies.scad",
  "./038-distributors-xrot_copies.scad",
  "./039-distributors-yrot_copies.scad",
  "./040-distributors-zrot_copies.scad",
  "./041-distributors-sphere_copies.scad",
  "./042-distributors-xflip_copy.scad",
  "./043-distributors-yflip_copy.scad",
  "./044-distributors-zflip_copy.scad",
  "./045-distributors-mirror_copy.scad",
  "./046-drawing-stroke.scad",
  "./047-fnliterals-echo.scad",
  "./048-gears-spur_gear.scad",
  "./049-gears-ring_gear.scad",
  "./050-gears-crown_gear.scad",
  "./051-gears-worm.scad",
  "./052-gears-enveloping_worm.scad",
  "./053-gears-worm_gear.scad",
  "./054-geometry-plane_from_normal.scad",
  "./055-geometry-sphere.scad",
  "./056-hinges-living_hinge_mask.scad",
  "./057-hinges-snap_lock.scad",
  "./058-hinges-snap_socket.scad",
  "./059-hooks-ring_hook.scad",
  "./060-joiners-half_joiner_clear.scad",
  "./061-joiners-joiner_clear.scad",
  "./062-joiners-dovetail.scad",
  "./063-joiners-cuboid.scad",
  "./064-joiners-snap_pin.scad",
  "./065-joiners-xcopies.scad",
  "./066-joiners-snap_pin_socket.scad",
  "./067-joiners-rabbit_clip.scad",
  "./068-joiners-hirth.scad",
  "./069-linalg-transpose.scad",
  "./070-linear_bearings-linear_bearing_housing.scad",
  "./071-linear_bearings-linear_bearing.scad",
  "./072-linear_bearings-lmXuu_housing.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
