"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../../lib/grid-utils.js')

const items = [
  "./dragon_and_pearl.scad",
  "./dragon_claw.scad",
  "./dragon_foot.scad",
  "./dragon_head.scad",
  "./dragon_head_low_poly.scad",
  "./dragon_scales.scad",
  "./hilbert_dragon.scad",
  "./hilbert_dragon_low_poly.scad",
  "./infinity_dragon.scad",
  "./mountain_dragon.scad",
  "./spiral_dragon.scad",
  "./torus_knot_dragon.scad",
  "./torus_knot_dragon_and_pearl.scad",
  "./torus_knot_dragon_low_poly.scad",
  "./treble_clef_dragon.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
