"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../lib/grid-utils.js')

const items = [
  "./01-two-cars.example.js",
  "./02-hierarchical-car.example.js",
  "./03-jscad.example.js",
  "./04-primitives.example.js",
  "./05-extrusions.example.js",
  "./06-hulls.example.js",
  "./07-gear.example.js",
  "./08-nuts-and-bolts.example.js",
  "./09-text.example.js",
  "./10-slicer.example.js",
  "./11-balloons.example.js",
  "./12-parameters.example.js",
  "./13-multipart.example.js",
  "./14-ttf-text.example.js",
  "./benchmarks/ALL.js"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
