"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../lib/grid-utils.js')

const items = [
  "./001-constants-cuboid.scad",
  "./002-constants-cyl.scad",
  "./003-involute_gears-gear.scad",
  "./004-involute_gears-rack.scad",
  "./005-joiners-half_joiner_clear.scad",
  "./006-joiners-half_joiner.scad",
  "./007-joiners-half_joiner2.scad",
  "./008-joiners-joiner_clear.scad",
  "./009-joiners-joiner.scad",
  "./010-joiners-joiner_pair_clear.scad",
  "./011-joiners-joiner_quad_clear.scad",
  "./012-linear_bearings-linear_bearing_housing.scad",
  "./013-linear_bearings-lmXuu_housing.scad",
  "./014-masks-angle_pie_mask.scad",
  "./015-masks-cylinder_mask.scad",
  "./016-masks-chamfer.scad",
  "./017-masks-chamfer_hole_mask.scad",
  "./018-masks-fillet.scad",
  "./019-masks-fillet_corner_mask.scad",
  "./020-masks-fillet_hole_mask.scad",
  "./021-math-sum.scad",
  "./022-math-sum_of_squares.scad",
  "./023-math-mean.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
