"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../lib/grid-utils.js')

const items = [
  "./Letter_A.scad",
  "./Lever_Handle.scad",
  "./Mallet.scad",
  "./Mech_Piece_01.scad",
  "./Mech_Piece_02.scad",
  "./Mech_Piece_03.scad",
  "./Mech_Piece_04.scad",
  "./Notebook.scad",
  "./Nut_LQ.scad",
  "./Pendulum.scad",
  "./Pipe_00.scad",
  "./Pipe_45.scad",
  "./Pipe_90.scad",
  "./Resistor.scad",
  "./Ring.scad",
  "./Rod_01.scad",
  "./Roll_Holder.scad",
  "./Sauce_Bottle.scad",
  "./Screw.scad",
  "./Shaft_01.scad",
  "./Shaft_02_With_Keyway.scad",
  "./Sign_01.scad",
  "./Sign_02.scad",
  "./Sign_03.scad",
  "./Soda_Cup_01.scad",
  "./Sofa.scad",
  "./Stairs_01.scad",
  "./Stairs_02.scad",
  "./Stairs_03.scad",
  "./Street_01.scad",
  "./Street_02.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
