"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script – loads each model under its own params namespace,
// normalises it to the grid cell size, and positions it in a grid.
const { gridPosition, normalizeAndPlace, urlToPartName } = require('../../../lib/grid-utils.js')

const items = [
  "./Letter_A.scad",
  "./Lever_Handle.scad",
  "./Mallet.scad",
  "./Mech_Piece_01.scad",
  "./Mech_Piece_02.scad",
  "./Mech_Piece_03.scad",
  "./Mech_Piece_04.scad",
  "./Notebook.scad",
  "./Nut_LQ.scad",
  "./Pendulum.scad",
  "./Pipe_00.scad",
  "./Pipe_45.scad",
  "./Pipe_90.scad",
  "./Resistor.scad",
  "./Ring.scad",
  "./Rod_01.scad",
  "./Roll_Holder.scad",
  "./Sauce_Bottle.scad",
  "./Screw.scad",
  "./Sign_01.scad",
  "./Sign_02.scad",
  "./Sign_03.scad",
  "./Soda_Cup_01.scad",
  "./Sofa.scad",
  "./Stairs_01.scad",
  "./Stairs_02.scad",
  "./Stairs_03.scad",
  "./Street_01.scad",
  "./Street_02.scad"
]
const spacing = 60
const cellSize = 51

const main = (params) => {
  const all = []
  const nameSeen = {}

  items.forEach((url, i) => {
    try {
      // Calculate grid position dynamically
      const [x, y] = gridPosition(i, items.length, spacing)

      // Derive unique part name from URL
      let name = urlToPartName(url)
      // Deduplicate: if the same name appears twice, append _2, _3, …
      if (nameSeen[name]) {
        nameSeen[name]++
        name = `${name}_${nameSeen[name]}`
      } else {
        nameSeen[name] = 1
      }

      const mod = require(url)
      const fn = (mod && mod.main) || (typeof mod === 'function' ? mod : null)
      if (typeof fn === 'function') {
        // For hierarchical models: pass child proxy
        // For legacy models: wrapLegacyModule detects child proxy and creates isolated state
        const geoms = [].concat(fn(params[name]))
        all.push(...normalizeAndPlace(geoms, x, y, cellSize))
      }
    } catch (err) {
      console.error('ALL: failed to load', url, err.message)
      throw new Error(`Failed to load ${url}: ${err.message}`)
    }
  })
  return all
}

module.exports = { main }
