"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../../lib/grid-utils.js')

const items = [
  "./fidget_boo.scad",
  "./fidget_cat.scad",
  "./fidget_heart.scad",
  "./fidget_polygon.scad",
  "./fidget_pumpkin.scad",
  "./fidget_skull.scad",
  "./fidget_star.scad",
  "./helix_lampshade.scad",
  "./spiral_plate.scad",
  "./spiral_polygons.scad",
  "./square_pursuit_3d.scad",
  "./stick_tower.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
