"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../../lib/grid-utils.js')

const items = [
  "./floor_stand.scad",
  "./floor_stand_symbol.scad",
  "./floor_stand_text.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
