"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../lib/grid-utils.js')

const items = [
  "./3d-function.scad",
  "./extrusion.scad",
  "./forma-candle-holder.scad",
  "./spiral-2d.scad",
  "./superformula.scad",
  "./sweep-drop.scad",
  "./sweep-path.scad",
  "./sweep-test.scad",
  "./toothed-belt.scad",
  "./trefoil-knot-sweep.scad",
  "./twisted-torus-ring.scad",
  "./wave-cylinder.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
