"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../../lib/grid-utils.js')

const items = [
  "./L_puzzle.scad",
  "./bauer_text_sphere.scad",
  "./golden_spiral_jigsaw_puzzle.scad",
  "./heart_chain.scad",
  "./lotus_like_flower.scad",
  "./moving_fish.scad",
  "./nautilus_shell.scad",
  "./rose.scad",
  "./seashell.scad",
  "./simple_seashell.scad",
  "./spiral_city.scad",
  "./spiral_math_constants.scad",
  "./spiral_ripples.scad",
  "./string_tetrahedron.scad",
  "./string_tetrahedrons.scad",
  "./text_sphere.scad",
  "./text_tower.scad",
  "./twist_bottle.scad",
  "./twist_taiji.scad",
  "./vx_spiral_text.scad",
  "./xmas_tree.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
