"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../lib/grid-utils.js')

const items = [
  "./bearing_hole_test.scad",
  "./bearing_test.scad",
  "./boxes_test.scad",
  "./gears_spur.scad",
  "./hardware_test.scad",
  "./involute_gear.scad",
  "./lego.scad",
  "./linear_bearing_test.scad",
  "./metric_fastners_test.scad",
  "./polyholes_test.scad",
  "./regular_shapes_test.scad",
  "./servos_test.scad",
  "./shapes_3d.scad",
  "./stepper_test.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
