"use strict"
// ⚠️  DO NOT EDIT THIS FILE - IT IS AUTO-GENERATED ⚠️
// This file is generated by bin/generate-all-files.js
// Any manual changes will be overwritten when the script runs.
//
// Auto-generated ALL script: runs each model under its own params namespace in
// one cell of a grid. See gridModule in lib/grid-utils.js.
const { gridModule } = require('../../../lib/grid-utils.js')

const items = [
  "./145-threading-ball_screw_rod.scad",
  "./146-transforms-xscale.scad",
  "./147-transforms-yscale.scad",
  "./148-transforms-zscale.scad",
  "./149-transforms-xflip.scad",
  "./150-transforms-yflip.scad",
  "./151-transforms-zflip.scad",
  "./152-transforms-frame_map.scad",
  "./153-transforms-skew.scad",
  "./154-tripod_mounts-manfrotto_rc2_plate.scad",
  "./155-utility-same_shape.scad",
  "./156-utility-assert_approx.scad",
  "./157-utility-assert_equal.scad",
  "./158-vectors-v_mul.scad",
  "./159-vectors-v_div.scad",
  "./160-vectors-v_abs.scad",
  "./161-vnf-echo.scad",
  "./162-walls-sparse_wall.scad",
  "./163-walls-sparse_wall2d.scad",
  "./164-walls-hex_panel.scad",
  "./165-walls-corrugated_wall.scad",
  "./166-walls-thinning_wall.scad",
  "./167-walls-thinning_triangle.scad",
  "./168-walls-narrowing_strut.scad",
  "./169-wiring-wire_bundle.scad",
  "./BOSL2logo.scad",
  "./attachments.scad",
  "./boolean_geometry.scad",
  "./fractal_tree.scad",
  "./lsystems.scad",
  "./orientations.scad",
  "./spherical_patch.scad",
  "./spring_handle.scad",
  "./worldmap_360x180.scad"
]

module.exports = gridModule(items, { spacing: 60, cellSize: 51 }, require)
